version: 2
updates:
  - package-ecosystem: "npm"
    rebase-strategy: "auto"
    directory: "/server"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    rebase-strategy: "auto"
    directory: "/client"
    schedule:
      interval: "daily"
